### ISSUE TITLE
Update `compile_yul` to return `None` when `solc` executable is not found

### ISSUE THREAD

**Issue by han0110** [privacy-scaling-explorations/snark-verifier#19]
Currently `compile_yul` panics without any helpful message if `solc` executable is not found.

https://github.com/privacy-scaling-explorations/plonk-verifier/blob/5e5de91c5dae319287e1bc30004a430ee74c915f/src/loader/evm/util.rs#L103-L120

We should instead return `None` when `solc` is missing if we want this API to be public (or make it private then panic with helpful message).

**Comment by mhh001** [comment]
Hi. Could I take this issue? I'd like to try this as my first request to become familiar with GitHub.
