### ISSUE TITLE
Private fields of `KzgDecider` get in the way of implementing new loaders

### ISSUE THREAD

**Issue by gnull** [privacy-scaling-explorations/snark-verifier#55]
Hi!

I ran into an issue trying to implement my own loader for Plonk with Kzg10. I was trying to `impl<M, MOS> AccumulationDecider<M::G1Affine, MyOwnLoader> for KzgAs<M, MOS>` analogously to

https://github.com/privacy-scaling-explorations/snark-verifier/blob/fedd7a8ffa44082c20a63e101484e0991ee7cce0/snark-verifier/src/pcs/kzg/decider.rs#L58

The problem is that the fields of `KzgDecidingKey` are private and `AccumulationDecider` implementations defined outside of `snark-verifier` can't use them:

https://github.com/privacy-scaling-explorations/snark-verifier/blob/fedd7a8ffa44082c20a63e101484e0991ee7cce0/snark-verifier/src/pcs/kzg/decider.rs#L6-L13

I'm guessing that this wasn't the intention, and I thought it can make the API more convenient to use if we exposed `g2` and `s_g2` to external `AccumulationDecider` implementations, so they could do something like this:

https://github.com/privacy-scaling-explorations/snark-verifier/blob/fedd7a8ffa44082c20a63e101484e0991ee7cce0/snark-verifier/src/pcs/kzg/decider.rs#L70

 Would you be willing to accept a PR for this? If so, which way of exposing the fields would you find most appropriate (making field pub, writing a getter method, an `Into` instance, etc.)?

Ivan

**Comment by han0110** [comment]
Hi, the use case sounds totally reasonable, feel free to open a PR to expose that!
